python -u run.py --task_name short_term_forecast --is_training 1 --root_path ./all_datasets/m4/ --seasonal_patterns Yearly --model_id m4_timemixer_Yearly --model TimeMixer --data m4 --enc_in 1 --loss SMAPE --e_layers 2 --d_model 64 --d_ff 128 --moving_avg 25 --down_sampling_layers 1 --down_sampling_window 2 --down_sampling_method avg --channel_independence 0 --decomp_method moving_avg --use_norm 1 --use_future_temporal_feature 0 --dropout 0.5 --itr 1 --learning_rate 0.0005 --batch_size 128 --train_epochs 100 --patience 10 --des Exp

python -u run.py --task_name short_term_forecast --is_training 1 --root_path ./all_datasets/m4/ --seasonal_patterns Monthly --model_id m4_timemixer_Monthly --model TimeMixer --data m4 --enc_in 1 --loss SMAPE --e_layers 2 --d_model 64 --d_ff 128 --moving_avg 25 --down_sampling_layers 1 --down_sampling_window 2 --down_sampling_method avg --channel_independence 0 --decomp_method moving_avg --use_norm 1 --use_future_temporal_feature 0 --dropout 0.0 --itr 1 --learning_rate 0.001 --batch_size 128 --train_epochs 100 --patience 10 --des Exp

python -u run.py --task_name short_term_forecast --is_training 1 --root_path ./all_datasets/m4/ --seasonal_patterns Quarterly --model_id m4_timemixer_Quarterly --model TimeMixer --data m4 --enc_in 1 --loss SMAPE --e_layers 2 --d_model 64 --d_ff 128 --moving_avg 25 --down_sampling_layers 1 --down_sampling_window 2 --down_sampling_method avg --channel_independence 0 --decomp_method moving_avg --use_norm 1 --use_future_temporal_feature 0 --dropout 0.0 --itr 1 --learning_rate 0.0005 --batch_size 64 --train_epochs 100 --patience 10 --des Exp

python -u run.py --task_name short_term_forecast --is_training 1 --root_path ./all_datasets/m4/ --seasonal_patterns Weekly --model_id m4_timemixer_Weekly --model TimeMixer --data m4 --enc_in 1 --loss SMAPE --e_layers 2 --d_model 64 --d_ff 128 --moving_avg 25 --down_sampling_layers 1 --down_sampling_window 2 --down_sampling_method avg --channel_independence 0 --decomp_method moving_avg --use_norm 1 --use_future_temporal_feature 0 --dropout 0.5 --itr 1 --learning_rate 0.0001 --batch_size 32 --train_epochs 100 --patience 10 --des Exp --lradj type3

python -u run.py --task_name short_term_forecast --is_training 1 --root_path ./all_datasets/m4/ --seasonal_patterns Daily --model_id m4_timemixer_Daily --model TimeMixer --data m4 --enc_in 1 --loss SMAPE --e_layers 2 --d_model 64 --d_ff 128 --moving_avg 25 --down_sampling_layers 1 --down_sampling_window 2 --down_sampling_method avg --channel_independence 0 --decomp_method moving_avg --use_norm 1 --use_future_temporal_feature 0 --dropout 0.0 --itr 1 --learning_rate 0.001 --batch_size 32 --train_epochs 100 --patience 10 --des Exp

python -u run.py --task_name short_term_forecast --is_training 1 --root_path ./all_datasets/m4/ --seasonal_patterns Hourly --model_id m4_timemixer_Hourly --model TimeMixer --data m4 --enc_in 1 --loss SMAPE --e_layers 2 --d_model 64 --d_ff 128 --moving_avg 25 --down_sampling_layers 1 --down_sampling_window 2 --down_sampling_method avg --channel_independence 0 --decomp_method moving_avg --use_norm 1 --use_future_temporal_feature 0 --dropout 0.3 --itr 1 --learning_rate 0.001 --batch_size 8 --train_epochs 100 --patience 10 --des Exp
